backend:
  name: git-gateway
  branch: main  # आपकी वेबसाइट की मेन ब्रांच

media_folder: "uploads"  # यहाँ आपके अपलोड किए गए इमेज और वीडियो सेव होंगे
public_folder: "/uploads"

collections:
  - name: "episodes"
    label: "Anime Episodes"
    folder: "episodes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Video URL", name: "video_url", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
